status support

diff --git a/etc/transport b/etc/transport
--- a/etc/transport
+++ b/etc/transport
@@ -88,6 +88,38 @@ stop() {
     return $RETVAL
 }
 
+
+status() {
+    echo "Status Kronometrix transport"
+
+    RETVAL=0
+
+    if [ "X${OS_NAME}" = "XSunOS" ]; then
+        echo " ${TRANSPORT}: \c"
+    else
+        echo -n " ${TRANSPORT}: "
+    fi
+
+    # check pid before start
+    if [ -f ${KRMX_LOG}/${TRANSPORT}.pid ]; then
+        kill -0 `cat ${KRMX_LOG}/${TRANSPORT}.pid` >/dev/null 2>&1
+        if [ $? -ne 1 ]; then
+            RETVAL=$?
+            PID=`cat ${KRMX_LOG}/${TRANSPORT}.pid`
+        else
+            RETVAL=1
+        fi
+        [ $RETVAL -eq 0 ] && echo "running, pid:$PID" || echo "not running"
+    else
+        # no pid files
+        RETVAL=1
+        [ $RETVAL -eq 0 ] && echo "ok" || echo "failed"
+    fi
+
+    return $RETVAL
+}
+
+
 case "$1" in
    start)
       start
@@ -99,8 +131,11 @@ case "$1" in
       stop
       start
       ;;
+   status)
+      status
+      ;;
    *)
-      echo "Usage: $0 {start|stop|restart}"
+      echo "Usage: $0 {start|stop|restart|status}"
       exit 1
 esac
 exit $RETVAL
