FreeBSD pkg install uninstall rc.conf proecessing

diff --git a/pkg/freebsd/pkg-deinstall b/pkg/freebsd/pkg-deinstall
--- a/pkg/freebsd/pkg-deinstall
+++ b/pkg/freebsd/pkg-deinstall
@@ -28,37 +28,35 @@ if [ $2 == "POST-DEINSTALL" ]; then
     # operate on date snapshot file
     cp ${RC_CONF} ${RC_CONF}.${DATE}
 
+    echo "step 1"
+    grep "^${SVC}_transport_enable=\"YES\"" ${RC_CONF}.${DATE} >/dev/null 2>&1
+    if [ $? -eq 0 ]; then
+        # remove the service
+        grep -v "^${SVC}_transport_enable=\"YES\"" ${RC_CONF}.${DATE} > ${RC_CONF}.${DATE}.tmp
+        mv ${RC_CONF}.${DATE}.tmp ${RC_CONF}.${DATE}
+    fi
+
+    echo "step 2"
+    grep "^${SVC}_user=\"krmx\"" ${RC_CONF}.${DATE} >/dev/null 2>&1
+    if [ $? -eq 0 ]; then
+        # remove the service
+        grep -v "^${SVC}_user=\"krmx\"" ${RC_CONF}.${DATE} > ${RC_CONF}.${DATE}.tmp
+        mv ${RC_CONF}.${DATE}.tmp ${RC_CONF}.${DATE}
+    fi
+
+    echo "step 3"
     grep "^${SVC}_enable=\"YES\"" ${RC_CONF} >/dev/null 2>&1
     if [ $? -eq 0 ]; then
         # remove the service
         grep -v "^${SVC}_enable=\"YES\"" ${RC_CONF}.${DATE} > ${RC_CONF}.${DATE}.tmp
-        mv ${RC_CONF}.${DATE}.tmp ${RC_CONF}
-        if [ $? -eq 1 ]; then
-            echo "Error: cannot uninstall service: ${SVC}, exit now"
-            exit 1
-        fi
+        mv ${RC_CONF}.${DATE}.tmp ${RC_CONF}.${DATE}
     fi
 
-    grep "^${SVC}_transport_enable=\"YES\"" ${RC_CONF} >/dev/null 2>&1
-    if [ $? -eq 0 ]; then
-        # remove the service
-        grep -v "^${SVC}_transport_enable=\"YES\"" ${RC_CONF}.${DATE} > ${RC_CONF}.${DATE}.tmp
-        mv ${RC_CONF}.${DATE}.tmp ${RC_CONF}
-        if [ $? -eq 1 ]; then
-            echo "Error: cannot uninstall service: ${SVC}_transport, exit now"
-            exit 1
-        fi
-    fi
-
-    grep "^${SVC}_user=\"krmx\"" ${RC_CONF} >/dev/null 2>&1
-    if [ $? -eq 0 ]; then
-        # remove the service
-        grep -v "^${SVC}_user=\"krmx\"" ${RC_CONF}.${DATE} > ${RC_CONF}.${DATE}.tmp
-        mv ${RC_CONF}.${DATE}.tmp ${RC_CONF}
-        if [ $? -eq 1 ]; then
-            echo "Error: cannot uninstall service: ${SVC}_user, exit now"
-            exit 1
-        fi
+    # remove the temp rc.conf
+    mv ${RC_CONF}.${DATE} ${RC_CONF}
+    if [ $? -eq 1 ]; then
+        echo "Error: cannot uninstall service: ${SVC}, exit now"
+        exit 1
     fi
 
 fi
