kronometrix service update

diff --git a/pkg/freebsd/pkg-install b/pkg/freebsd/pkg-install
--- a/pkg/freebsd/pkg-install
+++ b/pkg/freebsd/pkg-install
@@ -1,29 +1,6 @@
 #!/bin/sh
 
-
-
 RC_CONF=/etc/rc.conf
-
-if [ $2 == "POST-INSTALL" ]; then
-    chown -R krmx:krmx /opt/kronometrix/auth
-    cp /opt/kronometrix/auth/etc/rc/kronometrix_auth /etc/rc.d/
-    /etc/rc.d/kronometrix_auth onestart
-
-    # install service
-    grep kronometrix_auth ${RC_CONF} >/dev/null 2>&1
-
-    if [ $? -eq 1 ]; then
-        # add the service
-        echo "kronometrix_auth=\"YES\"" >> ${RC_CONF}
-        echo "kronometrix_auth_user=\"krmx\"" >> ${RC_CONF}
-        if [ $? -eq 1 ]; then
-            echo "Error: cannot activate service, exit now"
-            exit 1
-        fi
-    fi
-fi
-
-
 
 
 if [ $2 == "PRE-INSTALL" ]; then
@@ -47,4 +24,26 @@ if [ $2 == "POST-INSTALL" ]; then
     fi
     cp /opt/kronometrix/etc/rc/kronometrix* /etc/rc.d/
     /etc/rc.d/kronometrix onestart
+
+
+    # install service
+    grep kronometrix ${RC_CONF} >/dev/null 2>&1
+    if [ $? -eq 1 ]; then
+
+        # add the service
+        echo "kronometrix=\"YES\"" >> ${RC_CONF}
+        if [ $? -eq 1 ]; then
+            echo "Error: cannot activate service, exit now"
+            exit 1
+        fi
+
+        grep kronometrix_user ${RC_CONF} >/dev/null 2>&1 
+        if [ $? -eq 1 ]; then
+            echo "kronometrix_user=\"krmx\"" >> ${RC_CONF}
+            if [ $? -eq 1 ]; then
+                echo "Error: cannot activate service, exit now"
+                exit 1
+            fi
+        fi
+    fi
 fi
