pkg install deinstall hooks

diff --git a/pkg/freebsd/pkg-deinstall b/pkg/freebsd/pkg-deinstall
--- a/pkg/freebsd/pkg-deinstall
+++ b/pkg/freebsd/pkg-deinstall
@@ -1,5 +1,30 @@
 #!/bin/sh
 
+if [ $2 == "POST-DEINSTALL" ]; then
+    [ -f /etc/rc.d/kronometrix_auth ] && rm /etc/rc.d/kronometrix_auth
+
+    # uninstall service
+    SVC=kronometrix_auth
+    RC_CONF=/etc/rc.conf
+    DATE=`date +"%Y%m%d_%H%M%S"`
+
+    grep "$SVC" ${RC_CONF} >/dev/null 2>&1
+    if [ $? -eq 0 ]; then
+        cp ${RC_CONF} ${RC_CONF}.${DATE}
+        # remove the service
+        grep -v "$SVC" ${RC_CONF}.${DATE} > ${RC_CONF}.${DATE}.tmp
+        mv ${RC_CONF}.${DATE}.tmp ${RC_CONF}
+        if [ $? -eq 1 ]; then
+            echo "Error: cannot uninstall service: $SVC, exit now"
+            exit 1
+        fi
+    fi
+fi
+
+
+
+
+
 if [ $2 == "DEINSTALL" ]; then
     /etc/rc.d/kronometrix_transport onestop >/dev/null 2>&1
     /etc/rc.d/kronometrix onestop >/dev/null 2>&1
@@ -8,4 +33,47 @@ fi
 if [ $2 == "POST-DEINSTALL" ]; then
     [ -f /etc/rc.d/kronometrix_transport ] && rm /etc/rc.d/kronometrix_transport 
     [ -f /etc/rc.d/kronometrix ] && rm /etc/rc.d/kronometrix
+
+    # uninstall service
+    SVC=kronometrix
+    RC_CONF=/etc/rc.conf
+    DATE=`date +"%Y%m%d_%H%M%S"`
+
+    # operate on date snapshot file
+    cp ${RC_CONF} ${RC_CONF}.${DATE}
+
+    grep "$SVC=\"YES\"" ${RC_CONF} >/dev/null 2>&1
+    if [ $? -eq 0 ]; then
+        # remove the service
+        grep -v "$SVC=\"YES\"" ${RC_CONF}.${DATE} > ${RC_CONF}.${DATE}.tmp
+        mv ${RC_CONF}.${DATE}.tmp ${RC_CONF}
+        if [ $? -eq 1 ]; then
+            echo "Error: cannot uninstall service: $SVC, exit now"
+            exit 1
+        fi
+    fi
+
+    grep "$SVC_transport=\"YES\"" ${RC_CONF} >/dev/null 2>&1
+    if [ $? -eq 0 ]; then
+        # remove the service
+        grep -v "$SVC_transport=\"YES\"" ${RC_CONF}.${DATE} > ${RC_CONF}.${DATE}.tmp
+        mv ${RC_CONF}.${DATE}.tmp ${RC_CONF}
+        if [ $? -eq 1 ]; then
+            echo "Error: cannot uninstall service: $SVC_transport, exit now"
+            exit 1
+        fi
+    fi
+
+    grep "$SVC_user=\"krmx\"" ${RC_CONF} >/dev/null 2>&1
+    if [ $? -eq 0 ]; then
+        # remove the service
+        grep -v "$SVC_user=\"krmx\"" ${RC_CONF}.${DATE} > ${RC_CONF}.${DATE}.tmp
+        mv ${RC_CONF}.${DATE}.tmp ${RC_CONF}
+        if [ $? -eq 1 ]; then
+            echo "Error: cannot uninstall service: $SVC_user, exit now"
+            exit 1
+        fi
+    fi
+
+
 fi
