FreeBSD pkg install uninstall rc.conf proecessing

diff --git a/pkg/freebsd/pkg-install b/pkg/freebsd/pkg-install
--- a/pkg/freebsd/pkg-install
+++ b/pkg/freebsd/pkg-install
@@ -34,7 +34,7 @@ if [ $2 == "POST-INSTALL" ]; then
     chown -R krmx:krmx /opt/kronometrix
 
     # install kornometrix service
-    grep kronometrix ${RC_CONF} >/dev/null 2>&1
+    grep "^kronometrix_enable" ${RC_CONF} >/dev/null 2>&1
     if [ $? -eq 1 ]; then
 
         # add the service
@@ -43,14 +43,25 @@ if [ $2 == "POST-INSTALL" ]; then
             echo "Error: cannot activate service: kronometrix, exit now"
             exit 1
         fi
+    fi
 
-        grep kronometrix_user ${RC_CONF} >/dev/null 2>&1 
+    grep "^kronometrix_user" ${RC_CONF} >/dev/null 2>&1 
+    if [ $? -eq 1 ]; then
+        echo "kronometrix_user=\"krmx\"" >> ${RC_CONF}
         if [ $? -eq 1 ]; then
-            echo "kronometrix_user=\"krmx\"" >> ${RC_CONF}
-            if [ $? -eq 1 ]; then
-                echo "Error: cannot activate service: kronometrix_user, exit now"
-                exit 1
-            fi
+            echo "Error: cannot activate service: kronometrix_user, exit now"
+            exit 1
+        fi
+    fi
+
+    grep "^kronometrix_transport_enable" ${RC_CONF} >/dev/null 2>&1
+    if [ $? -eq 1 ]; then
+
+        # add the service
+        echo "kronometrix_transport_enable=\"YES\"" >> ${RC_CONF}
+        if [ $? -eq 1 ]; then
+            echo "Error: cannot activate service: kronometrix_transport, exit now"
+            exit 1
         fi
     fi
 
@@ -63,5 +74,5 @@ if [ $2 == "POST-INSTALL" ]; then
         ln -s /opt/kronometrix/etc/rc/kronometrix_transport /etc/rc.d/kronometrix_transport || :
     fi
 
-    /etc/rc.d/kronometrix onestart >/dev/null 2>&1
+    /etc/rc.d/kronometrix start >/dev/null 2>&1
 fi
